name: Deploy static site
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write SSH key
        run: |
          cat > key.pem <<'EOF'
          ${{ secrets.SSH_KEY }}
          EOF
          chmod 600 key.pem

      - name: SSH smoke test
        run: |
          ssh -i key.pem -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo OK'

      - name: Rsync to server
        run: |
          rsync -avz --delete --progress \
            -e "ssh -i key.pem -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ConnectTimeout=15" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET }}
